### ISSUE TITLE
Cannot calculate discount percentage with this step.

### ISSUE THREAD

**Issue by ghost** [Lake-e/iPad-Calculator#3]
**Step to reproduce :**
1. Input 100
2. Tap - 
3. Input 10
4. Tap %
5. Tap =

**Expected Result :** 90
**Actual Result :** 99.9

Note : These steps work fine in Calculator App in iPhone

**Comment by Lake-e** [comment]
Yes, this is an oversight in how I handle the percent button, which I have not gotten around to changing yet.
